### ISSUE TITLE
When trying to import in deno, a lot of missing dependency errors are thrown

### ISSUE THREAD

**Issue by zingi** [octokit/octokit.js#2075]
**What happened?**

  

I wanted to import `Octokit` in deno as described [here](https://github.com/octokit/octokit.js#usage).

```js
// index.js
import { Octokit } from "https://cdn.skypack.dev/octokit?dts";
console.log(Octokit)
```

```shell
deno run --reload index.js
```

but a lot of missing dependency errors were thrown:

<details>
<summary>Error Output</summary>

```
❯ deno run --reload index.js
Download https://cdn.skypack.dev/octokit?dts
Download https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=imports/optimized/octokit.js
Download https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-throttling@v3.4.1-1wb8QKI378sQiyvKtfsY/dist=es2020,mode=imports/optimized/@octokit/plugin-throttling.js
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=imports/optimized/@octokit/plugin-paginate-rest.js
Download https://cdn.skypack.dev/-/@octokit/plugin-rest-endpoint-methods@v5.0.0-3QK7Pkud3HXg1JaN9U2R/dist=es2020,mode=imports/optimized/@octokit/plugin-rest-endpoint-methods.js
Download https://cdn.skypack.dev/-/@octokit/core@v3.4.0-B1STqggIC5ttmjDndZOQ/dist=es2020,mode=imports/optimized/@octokit/core.js
Download https://cdn.skypack.dev/-/@octokit/plugin-retry@v3.0.7-QTlPSf0w8dfrSe38Ubqv/dist=es2020,mode=imports/optimized/@octokit/plugin-retry.js
Download https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=imports/optimized/@octokit/app.js
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=imports/optimized/@octokit/oauth-app.js
Download https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=types/dist-types/app.d.ts
Download https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=types/dist-types/octokit.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=imports/optimized/@octokit/webhooks.js
Download https://cdn.skypack.dev/-/@octokit/auth-unauthenticated@v2.0.4-UGRkBhHwjtk6IwF0KVLH/dist=es2020,mode=imports/optimized/@octokit/auth-unauthenticated.js
Download https://cdn.skypack.dev/-/@octokit/auth-app@v3.3.0-L28kvdoAOBuXVBXFSFLE/dist=es2020,mode=imports/optimized/@octokit/auth-app.js
Download https://cdn.skypack.dev/-/universal-user-agent@v6.0.0-fUAPE3UH5QP7qG0fd0dH/dist=es2020,mode=imports/optimized/universal-user-agent.js
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-app@v4.1.2-6kDSHkjPobc3v7EdDUrZ/dist=es2020,mode=imports/optimized/@octokit/auth-oauth-app.js
Download https://cdn.skypack.dev/-/fromentries@v1.3.2-xV12OVMQyK4Alyc7h6sI/dist=es2020,mode=imports/optimized/fromentries.js
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=imports/optimized/@octokit/oauth-methods.js
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-user@v1.2.4-U3ONGxl0F5X4hwkcomel/dist=es2020,mode=imports/optimized/@octokit/auth-oauth-user.js
Download https://cdn.skypack.dev/-/bottleneck@v2.19.5-WnyfIkTTdKNNPUEySJVJ/dist=es2020,mode=imports/unoptimized/light.js
Download https://cdn.skypack.dev/-/@octokit/graphql@v4.6.1-mNSFgiNLmVCz49dwB07r/dist=es2020,mode=imports/optimized/@octokit/graphql.js
Download https://cdn.skypack.dev/-/@octokit/auth-token@v2.4.5-jdaltUppqSSeF1LAakAf/dist=es2020,mode=imports/optimized/@octokit/auth-token.js
Download https://cdn.skypack.dev/-/@octokit/request@v5.4.15-4Kxn3F9Uik78AlVNJxI5/dist=es2020,mode=imports/optimized/@octokit/request.js
Download https://cdn.skypack.dev/-/before-after-hook@v2.2.1-ScsE5eGrAt3c0oni5495/dist=es2020,mode=imports/optimized/before-after-hook.js
Download https://cdn.skypack.dev/-/@octokit/core@v3.4.0-B1STqggIC5ttmjDndZOQ/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/core@v3.4.0-B1STqggIC5ttmjDndZOQ/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-device@v3.1.1-uMqCh6l8EAWhT0KGvrXK/dist=es2020,mode=imports/optimized/@octokit/auth-oauth-device.js
Download https://cdn.skypack.dev/-/btoa-lite@v1.0.0-EdoP2Wejbuei0whftaMM/dist=es2020,mode=imports/optimized/btoa-lite.js
Download https://cdn.skypack.dev/-/@octokit/endpoint@v6.0.11-Pwm5PA73fBTxFTywuiBB/dist=es2020,mode=imports/optimized/@octokit/endpoint.js
Download https://cdn.skypack.dev/-/is-plain-object@v5.0.0-8mrVMp9y5RYdpZYGe1Tt/dist=es2020,mode=imports/optimized/is-plain-object.js
Download https://cdn.skypack.dev/-/@octokit/request-error@v2.0.5-tcPOyvkNInacY9l6poxY/dist=es2020,mode=imports/optimized/@octokit/request-error.js
Download https://deno.land/std/node/crypto.ts
Download https://cdn.skypack.dev/-/aggregate-error@v3.1.0-SEj1cA2tvXZcRXebUHUI/dist=es2020,mode=imports/optimized/aggregate-error.js
Download https://cdn.skypack.dev/-/universal-github-app-jwt@v1.1.0-TxlnEhpSPAyjsOdxoA3m/dist=es2020,mode=imports/optimized/universal-github-app-jwt.js
Download https://cdn.skypack.dev/-/lru-cache@v6.0.0-IF3dXOIuVvZ6NoDdLuhR/dist=es2020,mode=imports/optimized/lru-cache.js
Download https://cdn.skypack.dev/-/deprecation@v2.3.1-uvOjAQiALAZPHmrlznlP/dist=es2020,mode=imports/optimized/deprecation.js
Download https://cdn.skypack.dev/-/@octokit/oauth-authorization-url@v4.3.1-zPhqywOTFe9chHuBbvUo/dist=es2020,mode=imports/optimized/@octokit/oauth-authorization-url.js
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/request-error@v2.0.5-tcPOyvkNInacY9l6poxY/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/core@v3.4.0-B1STqggIC5ttmjDndZOQ/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/once@v1.4.0-dZva3nt1fLBY6vpXF5Hj/dist=es2020,mode=imports/optimized/once.js
Download https://cdn.skypack.dev/-/indent-string@v4.0.0-oHjbEh2BQXR9CwWQa6OC/dist=es2020,mode=imports/optimized/indent-string.js
Download https://cdn.skypack.dev/-/clean-stack@v2.2.0-T6Q1GM86WL6IIYyWyZOC/dist=es2020,mode=imports/optimized/clean-stack.js
Download https://cdn.skypack.dev/-/yallist@v4.0.0-zGx9utyhIe9lDU5JvFtt/dist=es2020,mode=imports/optimized/yallist.js
Download https://cdn.skypack.dev/-/wrappy@v1.0.2-e8nLh7Qms0NRhbAbUpJP/dist=es2020,mode=imports/optimized/wrappy.js
Download https://cdn.skypack.dev/-/before-after-hook@v2.2.1-ScsE5eGrAt3c0oni5495/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/request@v5.4.15-4Kxn3F9Uik78AlVNJxI5/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/graphql@v4.6.1-mNSFgiNLmVCz49dwB07r/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/core@v3.4.0-B1STqggIC5ttmjDndZOQ/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/request-error@v2.0.5-tcPOyvkNInacY9l6poxY/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/request@v5.4.15-4Kxn3F9Uik78AlVNJxI5/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/graphql@v4.6.1-mNSFgiNLmVCz49dwB07r/dist=es2020,mode=types/dist-types/index.d.ts
Warning Implicitly using latest version (0.92.0) for https://deno.land/std/node/crypto.ts
Download https://deno.land/std@0.92.0/node/crypto.ts
Download https://cdn.skypack.dev/-/@octokit/graphql@v4.6.1-mNSFgiNLmVCz49dwB07r/dist=es2020,mode=types/dist-types/types.d.ts
Download https://deno.land/std@0.92.0/node/_crypto/randomBytes.ts
Download https://deno.land/std@0.92.0/node/buffer.ts
Download https://deno.land/std@0.92.0/hash/mod.ts
Download https://deno.land/std@0.92.0/encoding/hex.ts
Download https://deno.land/std@0.92.0/node/_crypto/pbkdf2.ts
Download https://deno.land/std@0.92.0/node/_stream/transform.ts
Download https://deno.land/std@0.92.0/node/stream.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestParameters.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/AuthInterface.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/Url.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/Fetch.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestOptions.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestHeaders.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/EndpointOptions.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestError.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/Route.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/EndpointInterface.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/GetResponseTypeFromEndpointMethod.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/EndpointDefaults.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestInterface.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestMethod.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/Signal.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/RequestRequestOptions.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/VERSION.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/ResponseHeaders.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/OctokitResponse.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/StrategyInterface.d.ts
Download https://cdn.skypack.dev/-/@octokit/types@v6.13.0-0W3jmHJ4BGsot2MQkZWZ/dist=es2020,mode=types/dist-types/generated/Endpoints.d.ts
Download https://cdn.skypack.dev/-/@octokit/request-error@v2.0.5-tcPOyvkNInacY9l6poxY/dist=es2020,mode=types/dist-types/types.d.ts
Download https://deno.land/std@0.92.0/node/_utils.ts
Download https://deno.land/std@0.92.0/encoding/base64.ts
Download https://deno.land/std@0.92.0/node/_stream/stream.ts
Download https://deno.land/std@0.92.0/node/_stream/passthrough.ts
Download https://deno.land/std@0.92.0/node/_stream/promises.ts
Download https://deno.land/std@0.92.0/node/_stream/end_of_stream.ts
Download https://deno.land/std@0.92.0/node/_stream/readable.ts
Download https://deno.land/std@0.92.0/node/_stream/writable.ts
Download https://deno.land/std@0.92.0/node/_stream/pipeline.ts
Download https://deno.land/std@0.92.0/node/_stream/duplex.ts
Download https://deno.land/std@0.92.0/node/_crypto/constants.ts
Download https://deno.land/std@0.92.0/node/_crypto/types.ts
Download https://deno.land/std@0.92.0/hash/hasher.ts
Download https://deno.land/std@0.92.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.92.0/node/_errors.ts
Download https://deno.land/std@0.92.0/node/_stream/writable_internal.ts
Download https://deno.land/std@0.92.0/testing/asserts.ts
Download https://deno.land/std@0.92.0/io/util.ts
Download https://deno.land/std@0.92.0/async/mod.ts
Download https://deno.land/std@0.92.0/node/util.ts
Download https://deno.land/std@0.92.0/node/events.ts
Download https://cdn.skypack.dev/-/@octokit/openapi-types@v6.0.0-cHQYdirlcLqCFKB7JXw3/dist=es2020,mode=types/index.d.ts
Download https://deno.land/std@0.92.0/node/_stream/symbols.ts
Download https://deno.land/std@0.92.0/hash/_wasm/wasm.js
Download https://deno.land/std@0.92.0/node/_stream/from.ts
Download https://deno.land/std@0.92.0/node/_stream/buffer_list.ts
Download https://deno.land/std@0.92.0/node/_stream/readable_internal.ts
Download https://deno.land/std@0.92.0/node/string_decoder.ts
Download https://deno.land/std@0.92.0/node/_stream/async_iterator.ts
Download https://deno.land/std@0.92.0/node/_stream/destroy.ts
Download https://deno.land/std@0.92.0/node/_stream/duplex_internal.ts
Download https://deno.land/std@0.92.0/io/buffer.ts
Download https://deno.land/std@0.92.0/fmt/colors.ts
Download https://deno.land/std@0.92.0/testing/_diff.ts
Download https://deno.land/std@0.92.0/async/deferred.ts
Download https://deno.land/std@0.92.0/async/pool.ts
Download https://deno.land/std@0.92.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.92.0/async/delay.ts
Download https://deno.land/std@0.92.0/_util/assert.ts
Download https://deno.land/std@0.92.0/node/_util/_util_callbackify.ts
Download https://deno.land/std@0.92.0/node/_util/_util_promisify.ts
Download https://deno.land/std@0.92.0/node/_util/_util_types.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/delete-authorization.d.ts
Download https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/check-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-rest-endpoint-methods@v5.0.0-3QK7Pkud3HXg1JaN9U2R/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/get-web-flow-authorization-url.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/create-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/reset-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/refresh-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/delete-token.d.ts
Download https://cdn.skypack.dev/error/unknown:@octokit/webhooks?from=octokit
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/get-user-octokit.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/methods/scope-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-rest-endpoint-methods@v5.0.0-3QK7Pkud3HXg1JaN9U2R/dist=es2020,mode=types/dist-types/generated/method-types.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-app@v4.1.2-6kDSHkjPobc3v7EdDUrZ/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-user@v1.2.4-U3ONGxl0F5X4hwkcomel/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/oauth-app-octokit.d.ts
Download https://cdn.skypack.dev/-/@octokit/openapi-types@v6.0.0-cHQYdirlcLqCFKB7JXw3/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/openapi-types@v6.0.0-cHQYdirlcLqCFKB7JXw3/dist=es2020,mode=types/dist-types/version.d.ts
Download https://cdn.skypack.dev/-/@octokit/openapi-types@v6.0.0-cHQYdirlcLqCFKB7JXw3/dist=es2020,mode=types/dist-types/generated/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-app@v4.1.2-6kDSHkjPobc3v7EdDUrZ/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-app@v4.1.2-6kDSHkjPobc3v7EdDUrZ/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/middleware/...d.ts
Download https://cdn.skypack.dev/error/http?from=@octokit/app
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=types/dist-types/compose-paginate.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=types/dist-types/paginating-endpoints.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-device@v3.1.1-uMqCh6l8EAWhT0KGvrXK/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-user@v1.2.4-U3ONGxl0F5X4hwkcomel/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/refresh-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/version.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/exchange-device-code.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/exchange-web-flow-code.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/get-web-flow-authorization-url.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/delete-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/scope-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/delete-authorization.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/check-token.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/create-device-code.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-methods@v1.2.2-jD9lUHb6Uxw4mEAYDuA6/dist=es2020,mode=types/dist-types/reset-token.d.ts
Download https://cdn.skypack.dev/error/http?from=@octokit/oauth-app
Download https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/middleware/node/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-paginate-rest@v2.13.3-3nV3SuQ7Ua8MHSui5kTk/dist=es2020,mode=types/dist-types/generated/paginating-endpoints.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-authorization-url@v4.3.1-zPhqywOTFe9chHuBbvUo/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-user@v1.2.4-U3ONGxl0F5X4hwkcomel/dist=es2020,mode=types/dist-types/requires-basic-auth.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-user@v1.2.4-U3ONGxl0F5X4hwkcomel/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/event-handler/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/verify/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/sign/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/generated/webhook-names.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks-definitions@v3.65.5-XixKjpjlyxIJw8OSOhZG/dist=es2020,mode=types/schema.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/createLogger.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-device@v3.1.1-uMqCh6l8EAWhT0KGvrXK/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/plugin-rest-endpoint-methods@v5.0.0-3QK7Pkud3HXg1JaN9U2R/dist=es2020,mode=types/dist-types/generated/parameters-and-response-types.d.ts
Download https://cdn.skypack.dev/-/@octokit/auth-oauth-device@v3.1.1-uMqCh6l8EAWhT0KGvrXK/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-authorization-url@v4.3.1-zPhqywOTFe9chHuBbvUo/dist=es2020,mode=types/dist-types/index.d.ts
Download https://cdn.skypack.dev/-/@octokit/oauth-authorization-url@v4.3.1-zPhqywOTFe9chHuBbvUo/dist=es2020,mode=types/dist-types/types.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/get-payload.d.ts
Download https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/types.d.ts
Download https://cdn.skypack.dev/error/unknown:node?from=@octokit/webhooks
Download https://cdn.skypack.dev/error/http?from=@octokit/webhooks
Check file:///Users/aaron/Downloads/deno_test/index.ts
error: TS2694 [ERROR]: Namespace '__' has no exported member 'Api'.
} & import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.0-3QK7Pkud3HXg1JaN9U2R/dist=es2020,mode=types/dist-types/types.d.ts").Api>;
                                                                                                                                ~~~
    at https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=types/dist-types/octokit.d.ts:4:129

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'IncomingMessage'.
import { IncomingMessage, ServerResponse } from "/error/http?from=@octokit/oauth-app";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/middleware/node/types.d.ts:2:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'ServerResponse'.
import { IncomingMessage, ServerResponse } from "/error/http?from=@octokit/oauth-app";
                          ~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/middleware/node/types.d.ts:2:27

TS2694 [ERROR]: Namespace '__' has no exported member 'IncomingMessage'.
    at https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:5:196

TS2694 [ERROR]: Namespace '__' has no exported member 'ServerResponse'.
    at https://cdn.skypack.dev/-/@octokit/oauth-app@v3.3.0-TQUK3MKiCoUClhCisnYQ/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:5:269

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'IncomingMessage'.
import { IncomingMessage } from "/error/http?from=@octokit/webhooks";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/get-payload.d.ts:2:10

TS2671 [ERROR]: Cannot augment module 'http' because it resolves to a non-module entity.
declare module 'http' {
               ~~~~~~
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/get-payload.d.ts:3:16

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'IncomingMessage'.
import { IncomingMessage, ServerResponse } from "/error/http?from=@octokit/webhooks";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/types.d.ts:2:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'ServerResponse'.
import { IncomingMessage, ServerResponse } from "/error/http?from=@octokit/webhooks";
                          ~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/types.d.ts:2:27

TS2694 [ERROR]: Namespace '__' has no exported member 'IncomingMessage'.
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:6:178

TS2694 [ERROR]: Namespace '__' has no exported member 'ServerResponse'.
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:6:250

TS2688 [ERROR]: Cannot find type definition file for '/error/unknown:node?from=@octokit/webhooks'.
/// <reference types="/error/unknown:node?from=@octokit/webhooks" />
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/webhooks@v9.0.0-beta.3-oxnmNOopjs72FJOjIhBG/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:3:23

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'IncomingMessage'.
import { IncomingMessage, ServerResponse } from "/error/http?from=@octokit/app";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:2:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'ServerResponse'.
import { IncomingMessage, ServerResponse } from "/error/http?from=@octokit/app";
                          ~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:2:27

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'App'.
import { App } from "../...d.ts";
         ~~~
    at https://cdn.skypack.dev/-/@octokit/app@v11.4.1-gWU9ujRd97F2jEDGwkLC/dist=es2020,mode=types/dist-types/middleware/node/index.d.ts:3:10

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:@octokit/webhooks?from=octokit"' has no exported member 'Webhooks'.
    webhooks: import("/error/unknown:@octokit/webhooks?from=octokit").Webhooks<{
                                                                      ~~~~~~~~
    at https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=types/dist-types/app.d.ts:7:71

TS2305 [ERROR]: Module '"https://cdn.skypack.dev/-/octokit@v1.0.0-Ne7e9smG1qfLZEXbDzkT/dist=es2020,mode=types/dist-types/index.d.ts"' has no exported member 'Action'.
import { Octokit, App, Action } from "https://cdn.skypack.dev/octokit?dts";
                       ~~~~~~
    at file:///Users/aaron/Downloads/deno_test/index.ts:1:24

Found 17 errors.
```

</details>

What am I doing wrong?

**What did you expect to happen?**

no missing dependency errors
  

**Environment**

```
❯ deno --version            
deno 1.8.3 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by sant123** [comment]
Interesting, I just copied the code above and get these errors:

![image](https://user-images.githubusercontent.com/7959437/115155497-d3b56480-a045-11eb-9afa-7f049e5f533f.png)

**Comment by laughedelic** [comment]
Same here

**Comment by laughedelic** [comment]
@gr2m I don't know if it's related, but I had a similar issue when I tried adding the throttling plugin to the octokit/core. If I run this script:

```typescript
import { Octokit } from "https://cdn.skypack.dev/@octokit/core";
import { throttling } from "https://cdn.skypack.dev/@octokit/plugin-throttling";
const MyOctokit = Octokit.plugin(throttling);
const octokit = new MyOctokit({
  auth: Deno.env.get("GITHUB_TOKEN"),
  throttle: {
    onRateLimit: (retryAfter: any, options: any, octokit: any) => {
      return true;
    },
    onAbuseLimit: (retryAfter: any, options: any, octokit: any) => {
      octokit.log.warn(`Abuse detected for request ${options.method} ${options.url}`);
    },
  },
});

octokit.log.warn("foo");
```

It prints `foo` and hangs. If I remove everything related `throttling`, it prints the message and exits.

A workaround for this hanging is to add `Deno.exit(0)` at the end.

**Comment by zingi** [comment]
> ```ts
> import { App } from "https://cdn.skypack.dev/octokit?dts";
> 
> const app = new App({
>   appId: "",
>   privateKey: "",
> });
> 
> app.log.warn("ok");
> ```

Can it be, that it set ups some unintended webhooks by default and just waits?

**Comment by gr2m** [comment]
no, it doesn't do anything like that. You have to call `app.webhooks.receive()` explicitly to receive an event. There should be no side effects in the constructor. 

The same does not happen when I run the code in Node, so I'm curious if you know of any tricks on how to debug it in Deno?

**Comment by sant123** [comment]
@gr2m do you think this issue may be reopened?

**Comment by gr2m** [comment]
I'd rather not reopen the issue, the original errors were addressed. But here is a follow up issue: #2079. I'd very much appreciate help with further narrowing down the problem. It's likely caused by `bottleneck`

**Comment by laughedelic** [comment]
@gr2m I think the original issue is still there for the `Api` and `Webhook` types: https://github.com/octokit/octokit.js/issues/2075#issuecomment-822032795.

**Comment by gr2m** [comment]
Hmm ok 😌 I didn't see these errors when I tested it the other day. Maybe it was caused by the upgrade to deno 1.9?

```
error: TS2694 [ERROR]: Namespace '__' has no exported member 'Api'.
} & import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.0-Ys4b4gg8pre8whHLrZxI/dist=es2020,mode=types/dist-types/types.d.ts").Api>;
                                                                                                                                ~~~
    at https://cdn.skypack.dev/-/octokit@v1.0.3-mEz0ql7OVdAy5fZlGuMp/dist=es2020,mode=types/dist-types/octokit.d.ts:4:129

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:@octokit/webhooks?from=octokit"' has no exported member 'Webhooks'.
    webhooks: import("/error/unknown:@octokit/webhooks?from=octokit").Webhooks<{
                                                                      ~~~~~~~~
    at https://cdn.skypack.dev/-/octokit@v1.0.3-mEz0ql7OVdAy5fZlGuMp/dist=es2020,mode=types/dist-types/app.d.ts:7:71

Found 2 errors.
```

I feel like we are going circles, this might be a new error, or I don't know what's going on here. I'd appreciate help debugging this, I can't really spent much time on it right now myself

**Comment by sant123** [comment]
Well, after some hours I figured out something curious and want to know **WHY** this happens:

This is the original error:
![image](https://user-images.githubusercontent.com/7959437/115972327-4e352700-a513-11eb-880b-96e8dba3e43c.png)

With this code in Visual Studio Code, press F12 in the import:
![image](https://user-images.githubusercontent.com/7959437/115972361-791f7b00-a513-11eb-9662-87ced4f3ea1c.png)

![image](https://user-images.githubusercontent.com/7959437/115972368-83da1000-a513-11eb-8ff6-9ea88736eeb0.png)

Now press F12 for `"./octokit.d.ts"`
![image](https://user-images.githubusercontent.com/7959437/115972392-abc97380-a513-11eb-96de-95230527d7e6.png)

To edit that code you need to open this file `41c8d1733b6c430f2629270b59ebf5b211d17bc5bbda3db924e216c84d535f75` in $HOME/.cache/deno/deps/https/cdn.skypack.dev

Copy this code and replace everything in the file with it:

``` typescript
import { Octokit as OctokitCore } from "/-/@octokit/core@v3.4.0-W4C5uhmyc4wSCIVwJnEX/dist=es2020,mode=types/index.d.ts";
export declare type SomeType = import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.1-JhiMRw570hyrJ3A8wvFD/dist=es2020,mode=types/dist-types/types.d.ts").Api;
export declare const Octokit: typeof OctokitCore & import("/-/@octokit/core@v3.4.0-W4C5uhmyc4wSCIVwJnEX/dist=es2020,mode=types/dist-types/types.d.ts").Constructor<void & {
    paginate: import("/-/@octokit/plugin-paginate-rest@v2.13.3-lPFWwUv4qPYxQ84z3Xin/dist=es2020,mode=types/index.d.ts").PaginateInterface;
} & SomeType>;
export declare type Octokit = InstanceType<typeof Octokit>;
```
Notice how we moved the type `import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.1-JhiMRw570hyrJ3A8wvFD/dist=es2020,mode=types/dist-types/types.d.ts").Api` into a type declaration.

Now run `deno cache mod.ts`

![image](https://user-images.githubusercontent.com/7959437/115972501-49bd3e00-a514-11eb-9fc4-6ce9e83e5686.png)

The first error is gone and maybe the same approach would be necessary for the second one, the question is why this happens? Is it something Deno Typescript cannot resolve under the hood? 

@gr2m @laughedelic any ideas??? 

Thank you for reading this long comment.

**Comment by gr2m** [comment]
Thanks @sant123, I really appreciate you helping to get to the bottom of this problem. 

~~Can you share the source code of `mod.ts`~~ nevermind, I missed the screenshot, sorry!

What version of `deno` you are using?

**Comment by gr2m** [comment]
> To edit that code you need to open this file `41c8d1733b6c430f2629270b59ebf5b211d17bc5bbda3db924e216c84d535f75` in $HOME/.cache/deno/deps/https/cdn.skypack.dev

In my case it's `~/Library/Caches/deno/deps/https/cdn.skypack.dev`. There is no `41c8d1733b6c430f2629270b59ebf5b211d17bc5bbda3db924e216c84d535f75` file. How can I find out which file you mean?

**Comment by sant123** [comment]
> Thanks @sant123, I really appreciate you helping to get to the bottom of this problem. 
> 
> 
> 
> ~~Can you share the source code of `mod.ts`~~ nevermind, I missed the screenshot, sorry!
> 
> 
> 
> What version of `deno` you are using?

You welcome 😁 currently I'm using the latest version as this date: v1.9.2

**Comment by sant123** [comment]
> > To edit that code you need to open this file `41c8d1733b6c430f2629270b59ebf5b211d17bc5bbda3db924e216c84d535f75` in $HOME/.cache/deno/deps/https/cdn.skypack.dev
> 
> 
> 
> In my case it's `~/Library/Caches/deno/deps/https/cdn.skypack.dev`. There is no `41c8d1733b6c430f2629270b59ebf5b211d17bc5bbda3db924e216c84d535f75` file. How can I find out which file you mean?
> 
> 

Well, I had to open each file inside that folder until I get the right one... didn't find a pattern to get the specific one.

**Comment by gr2m** [comment]
I think the key problem between the code `octokit.d.ts` and your fix is the version of `@octokit/plugin-rest-endpoint-methods`. It seems that deno gets 5.0.0, which had a typescript bug, it was resolved in 5.0.1.

Let me try trigger a new pre-release that will require 5.0.1 and see if that helps. The skypack folks say that the builds of dependants should get updated if one of their in-range dependencies has an update, but that doesn't work, at least not for the @octokit packages, so we have to explicitly do new releases for these cases for now

**Comment by gr2m** [comment]
I published `octokit@1.0.3-debug.1`. Can you check with this code?

```ts
import { App } from "https://cdn.skypack.dev/octokit@1.0.3-debug.1?dts";

const app = new App({
  appId: "",
  privateKey: "",
});

app.log.warn("ok");
```

**Comment by gr2m** [comment]
@sant123 @laughedelic ☝🏼

**Comment by gr2m** [comment]
I no longer see an error, but the process still hangs. Any idea how to debug it? Does Deno have a way to show a list of open sockets or whatever could keep a process from closing gracefully?

**Comment by sant123** [comment]
> I think the key problem between the code `octokit.d.ts` and your fix is the version of `@octokit/plugin-rest-endpoint-methods`. It seems that deno gets 5.0.0, which had a typescript bug, it was resolved in 5.0.1.
> 
> Let me try trigger a new pre-release that will require 5.0.1 and see if that helps. The skypack folks say that the builds of dependants should get updated if one of their in-range dependencies has an update, but that doesn't work, at least not for the @octokit packages, so we have to explicitly do new releases for these cases for now

Well I took a look and was using 5.0.1 version of `@octokit/plugin-rest-endpoint-methods` when I did the tests. But the error disappears when we apply the fix I did

**Comment by sant123** [comment]
> I published `octokit@1.0.3-debug.1`. Can you check with this code?
> 
> ```ts
> import { App } from "https://cdn.skypack.dev/octokit@1.0.3-debug.1?dts";
> 
> const app = new App({
>   appId: "",
>   privateKey: "",
> });
> 
> app.log.warn("ok");
> ```

I just checked it and having the same 2 errors 😞

**Comment by gr2m** [comment]
ugh me to, when I run it with `--reload`. How is this possible 😭

**Comment by sant123** [comment]
> I no longer see an error, but the process still hangs. Any idea how to debug it? Does Deno have a way to show a list of open sockets or whatever could keep a process from closing gracefully?

I still can't debug it @gr2m, but this may help https://deno.land/manual/contributing/architecture#resources

**Comment by sant123** [comment]
> ugh me to, when I run it with `--reload`. How is this possible sob

I checked with both `run` and `cache` commands with the `--reload` flag and getting the same issue 😕

**Comment by sant123** [comment]
> Well, after some hours I figured out something curious and want to know **WHY** this happens:
> 
> This is the original error:
> ![image](https://user-images.githubusercontent.com/7959437/115972327-4e352700-a513-11eb-880b-96e8dba3e43c.png)
> 
> With this code in Visual Studio Code, press F12 in the import:
> ![image](https://user-images.githubusercontent.com/7959437/115972361-791f7b00-a513-11eb-9662-87ced4f3ea1c.png)
> 
> ![image](https://user-images.githubusercontent.com/7959437/115972368-83da1000-a513-11eb-8ff6-9ea88736eeb0.png)
> 
> Now press F12 for `"./octokit.d.ts"`
> ![image](https://user-images.githubusercontent.com/7959437/115972392-abc97380-a513-11eb-96de-95230527d7e6.png)
> 
> To edit that code you need to open this file `41c8d1733b6c430f2629270b59ebf5b211d17bc5bbda3db924e216c84d535f75` in $HOME/.cache/deno/deps/https/cdn.skypack.dev
> 
> Copy this code and replace everything in the file with it:
> 
> ```ts
> import { Octokit as OctokitCore } from "/-/@octokit/core@v3.4.0-W4C5uhmyc4wSCIVwJnEX/dist=es2020,mode=types/index.d.ts";
> export declare type SomeType = import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.1-JhiMRw570hyrJ3A8wvFD/dist=es2020,mode=types/dist-types/types.d.ts").Api;
> export declare const Octokit: typeof OctokitCore & import("/-/@octokit/core@v3.4.0-W4C5uhmyc4wSCIVwJnEX/dist=es2020,mode=types/dist-types/types.d.ts").Constructor<void & {
>     paginate: import("/-/@octokit/plugin-paginate-rest@v2.13.3-lPFWwUv4qPYxQ84z3Xin/dist=es2020,mode=types/index.d.ts").PaginateInterface;
> } & SomeType>;
> export declare type Octokit = InstanceType<typeof Octokit>;
> ```
> 
> Notice how we moved the type `import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.1-JhiMRw570hyrJ3A8wvFD/dist=es2020,mode=types/dist-types/types.d.ts").Api` into a type declaration.
> 
> Now run `deno cache mod.ts`
> 
> ![image](https://user-images.githubusercontent.com/7959437/115972501-49bd3e00-a514-11eb-9fc4-6ce9e83e5686.png)
> 
> The first error is gone and maybe the same approach would be necessary for the second one, the question is why this happens? Is it something Deno Typescript cannot resolve under the hood?
> 
> @gr2m @laughedelic any ideas???
> 
> Thank you for reading this long comment.

@gr2m please try this, it may take sometime while you find the right file but once you have it, you can edit it in VSCode.

**Comment by gr2m** [comment]
The problem I'm having now is that I don't get the error when I run `deno cache mod.ts`, I only get it when I run `deno cache --reload mod.ts`, so I cannot edit the cached files because they are not used 😭

**Comment by gr2m** [comment]
nevermind, even with `--reload` the cached file seems to be used, the first error went away. I'm investigating why now

**Comment by gr2m** [comment]
Okay I confirmed that the simple change from

```ts
import { Octokit as OctokitCore } from "/-/@octokit/core@v3.4.0-RitNLHu7nhRy0a2lxxr8/dist=es2020,mode=types/index.d.ts";
export declare const Octokit: typeof OctokitCore &
  import("/-/@octokit/core@v3.4.0-RitNLHu7nhRy0a2lxxr8/dist=es2020,mode=types/dist-types/types.d.ts").Constructor<
    void & {
      paginate: import("/-/@octokit/plugin-paginate-rest@v2.13.3-Kxl5gKAMfpguk13T9qFz/dist=es2020,mode=types/index.d.ts").PaginateInterface;
    } & import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.1-Glf9sGLzvmq9Gzy3HXLt/dist=es2020,mode=types/dist-types/types.d.ts").Api
  >;
export declare type Octokit = InstanceType<typeof Octokit>;
```

to using `export declare type SomeType`

```ts
import { Octokit as OctokitCore } from "/-/@octokit/core@v3.4.0-RitNLHu7nhRy0a2lxxr8/dist=es2020,mode=types/index.d.ts";
export declare type SomeType = import("/-/@octokit/plugin-rest-endpoint-methods@v5.0.1-Glf9sGLzvmq9Gzy3HXLt/dist=es2020,mode=types/dist-types/types.d.ts").Api;
export declare const Octokit: typeof OctokitCore &
  import("/-/@octokit/core@v3.4.0-RitNLHu7nhRy0a2lxxr8/dist=es2020,mode=types/dist-types/types.d.ts").Constructor<
    void & {
      paginate: import("/-/@octokit/plugin-paginate-rest@v2.13.3-Kxl5gKAMfpguk13T9qFz/dist=es2020,mode=types/index.d.ts").PaginateInterface;
    } & SomeType
  >;
export declare type Octokit = InstanceType<typeof Octokit>;
```

resolves the first issue. Unfortunately this is generated code, we do not have control over it. Also ... any idea why this is a problem?

**Comment by sant123** [comment]
Unfortunately I don't know @gr2m. However I tested the package with ts-node and works pretty good. That's why I said maybe is it a Deno Typescript bug?

**Comment by laughedelic** [comment]
Hi! thanks for pinging me. I'm watching your progress, but can't really help, I'm totally new to all this and have no idea how any of it works.

Could it be a Skypack bug? They generate this code, if I understand correctly. I tried using `jspm`:

```typescript
import { App } from "https://jspm.dev/octokit@1.0.3-debug.1?dts";

const app = new App({
  appId: "",
  privateKey: "",
});

app.log.warn("ok");
```

And got a different error:

```
error: Uncaught SyntaxError: The requested module '/npm:universal-github-app-jwt@1!cjs' does not provide an export named 'default'
import _universalGithubAppJwt from '/npm:universal-github-app-jwt@1!cjs';
       ~~~~~~~~~~~~~~~~~~~~~~
    at <anonymous> (https://jspm.dev/npm:@octokit/auth-app@3.3.0!cjs:5:8)
```

This can probably be resolved with some modifications (`exports`?) in the `package.json` of that module, so I wonder if after that it will work 🤔 that would mean that jspm generates some other code that works.

**Comment by gr2m** [comment]
> This can probably be resolved with some modifications (`exports`?) in the `package.json` of that module

I am exploring a migration to native ES modules, but that is a bigger project. Unfortunately we are currently using [`@pika/pack`](https://github.com/snowpackjs/pack) for building all the @octokit modules. It was great at its time, but it's no longer maintained.

As an in-between step I'd be open to replace `@pika/pack` with another build setup which takes TypeScript code as input and spits out a directory with different builds, one with types, ideally two different ones for CJS,/ESM, and optionally one for browsers and deno, depending on necessity, and that sets the `exports` map in `package.json` accordingly.

**Comment by wperron** [comment]
For those looking for a quick workaround to just get their code running, `--no-check` gets rid of the error messages

**Comment by sant123** [comment]
> > This can probably be resolved with some modifications (`exports`?) in the `package.json` of that module
> 
> I am exploring a migration to native ES modules, but that is a bigger project. Unfortunately we are currently using [`@pika/pack`](https://github.com/snowpackjs/pack) for building all the @octokit modules. It was great at its time, but it's no longer maintained.
> 
> As an in-between step I'd be open to replace `@pika/pack` with another build setup which takes TypeScript code as input and spits out a directory with different builds, one with types, ideally two different ones for CJS,/ESM, and optionally one for browsers and deno, depending on necessity, and that sets the `exports` map in `package.json` accordingly.

What about using Rollup for that? It supports ESM generation by default and CJS via plugin.

**Comment by gr2m** [comment]
> What about using Rollup for that

`@pika/pack` is using rollup. I'm open to suggestions to replace `@pika/pack` with our own build script that we use across all @octokit libraries. We have control over most of our dependencies, the ones that didn't move to ESM yet we can easily replace.

**Comment by wperron** [comment]
If pika worked well, might be worth looking at https://github.com/snowpackjs/snowpack since it's the newer ESM bundler from the same folks. Skypack literally replaced the Pika cdn.

**Comment by gr2m** [comment]
I know snowpack, I worked with them for a while :) It's a different scope, we need a build setup for universal packages, not a frontend build tool.

**Comment by Ring2381** [comment]
Hi

**Comment by CryogenicPlanet** [comment]
Any updates on this?

Still running into these errors while using `export { Octokit, App } from "https://cdn.skypack.dev/octokit?dts"`
![image](https://user-images.githubusercontent.com/10355479/138574666-fb2c4c13-a194-406a-8e31-a9c7d819ce1b.png)

**Comment by gr2m** [comment]
We started work on https://github.com/octokit/octokit-next.js which, among other things, is all Native ESM so we hope it will work with Deno and other modern JavaScript Runtime Environments without a problem. However, work on Octokit is on hold right now I'm afraid: https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174

**Comment by Jolg42** [comment]
I also get the same issue here when using `import { Octokit } from "https://cdn.skypack.dev/octokit?dts";`
```
error: TS2694 [ERROR]: Namespace '__' has no exported member 'Api'.
} & import("/-/@octokit/plugin-rest-endpoint-methods@v5.13.0-qozG4mqmlmmkbkX9Donu/dist=es2019,mode=types/dist-types/types.d.ts").Api & {
                                                                                                                                 ~~~
    at https://cdn.skypack.dev/-/octokit@v1.7.1-1PoRQSXdCDkLMTIDPwfX/dist=es2019,mode=types/dist-types/octokit.d.ts:4:130
```

My workaround is to import it like this but I have no types available
```
import { Octokit } from "https://cdn.skypack.dev/@octokit/core";
const octokit = new Octokit({ auth: token });
```

But good news, I see that there is now a SDK team 👀 

> Hi everyone! :wave: 
> 
> I am excited to announce that GitHub is building a dedicated SDK team that will actively maintain all Octokit libraries (JS, Ruby, and .NET). The team’s mission will be to maintain, improve, and create Octokit libraries that will delight developers and improve GitHub’s ecosystem.
> 
> Our first role on the SDK team is now open and available [here](https://boards.greenhouse.io/github/jobs/3917118). If you’re interested, I’d love to chat with you!

https://github.com/octokit/octokit.js/discussions/620#discussioncomment-2144643

**Comment by jpilkahn** [comment]
@wperron

> For those looking for a quick workaround to just get their code running, `--no-check` gets rid of the error messages

`-- no-check`  skips type checking of modules entirely. `--no-check=remote` should suffice as a workaround without completely disabling checking for `deno run` or `deno bundle`.

From `deno run --help`:

```--no-check=<NO_CHECK_TYPE>...
Skip type checking of modules.
If the value of '--no-check=remote' is supplied, diagnostic errors from remote
modules will be ignored.```

**Comment by Adidi** [comment]
In the latest Deno version you can import pacakges from npm so this:
`import { App, Octokit } from "npm:octokit@^2.0.10";`
is working correctly.

**Comment by michaelwooley** [comment]
Similar to @Adidi, I've found that the npm specifier appears to yield expected objects and types.[1]

However, worth pointing out that [npm specifiers are only partially "stabilized."](https://deno.land/manual@v1.29.4/node/npm_specifiers#using-npm-packages-with-npm-specifiers) Note that:

- Requires `deno>=1.28`
- Will not work with `deno bundle`

The npm specifiers roadmap issue is: https://github.com/denoland/deno/issues/15960

_I think it would be helpful to add this alternative import (with a big asterisk `*`) in the readme._ Happy to open the PR if this sounds reasonable.

---

[1] In general, skypack is acting rather odd for me. The search functionality in the web ui isn't working. The [last blog post was in 2021.](https://www.skypack.dev/blog) It looks like the relevant packages are up to date. But it seems like something might be off if they are sunsetting or similar?

**Comment by wolfy1339** [comment]
Great to hear that things are working better with deno when using the npm specifiers!

PRs to update documentation are always welcome

**Comment by wolfy1339** [comment]
Using the following import map, I got no errors when running `deno check`
```json
{
  "imports": {
    "octokit": "https://esm.sh/v135/*octokit@4.1.0?target=deno",
    "_http_agent": "node:_http_agent",
    "_http_client": "node:_http_client",
    "_http_common": "node:_http_common",
    "_http_incoming": "node:_http_incoming",
    "_http_outgoing": "node:_http_outgoing",
    "_http_server": "node:_http_server",
    "_stream_duplex": "node:_stream_duplex",
    "_stream_passthrough": "node:_stream_passthrough",
    "_stream_readable": "node:_stream_readable",
    "_stream_transform": "node:_stream_transform",
    "_stream_wrap": "node:_stream_wrap",
    "_stream_writable": "node:_stream_writable",
    "_tls_common": "node:_tls_common",
    "_tls_wrap": "node:_tls_wrap",
    "assert": "node:assert",
    "assert/strict": "node:assert/strict",
    "async_hooks": "node:async_hooks",
    "buffer": "node:buffer",
    "child_process": "node:child_process",
    "cluster": "node:cluster",
    "console": "node:console",
    "constants": "node:constants",
    "crypto": "node:crypto",
    "dgram": "node:dgram",
    "diagnostics_channel": "node:diagnostics_channel",
    "dns": "node:dns",
    "dns/promises": "node:dns/promises",
    "domain": "node:domain",
    "events": "node:events",
    "fs": "node:fs",
    "fs/promises": "node:fs/promises",
    "http": "node:http",
    "http2": "node:http2",
    "https": "node:https",
    "inspector": "node:inspector",
    "inspector/promises": "node:inspector/promises",
    "module": "node:module",
    "net": "node:net",
    "os": "node:os",
    "path": "node:path",
    "path/posix": "node:path/posix",
    "path/win32": "node:path/win32",
    "perf_hooks": "node:perf_hooks",
    "process": "node:process",
    "punycode": "node:punycode",
    "querystring": "node:querystring",
    "readline": "node:readline",
    "readline/promises": "node:readline/promises",
    "repl": "node:repl",
    "stream": "node:stream",
    "stream/consumers": "node:stream/consumers",
    "stream/promises": "node:stream/promises",
    "stream/web": "node:stream/web",
    "string_decoder": "node:string_decoder",
    "sys": "node:sys",
    "timers": "node:timers",
    "timers/promises": "node:timers/promises",
    "tls": "node:tls",
    "trace_events": "node:trace_events",
    "tty": "node:tty",
    "url": "node:url",
    "util": "node:util",
    "util/types": "node:util/types",
    "v8": "node:v8",
    "vm": "node:vm",
    "wasi": "node:wasi",
    "worker_threads": "node:worker_threads",
    "zlib": "node:zlib"
  },
  "scopes": {
    "https://esm.sh/v135/": {
      "@octokit/app": "https://esm.sh/v135/@octokit/app@15.1.2?target=deno",
      "@octokit/auth-app": "https://esm.sh/v135/@octokit/auth-app@7.1.4?target=deno",
      "@octokit/auth-unauthenticated": "https://esm.sh/v135/@octokit/auth-unauthenticated@6.1.1?target=deno",
      "@octokit/core": "https://esm.sh/v135/@octokit/core@6.1.3?target=deno",
      "@octokit/core/types": "https://esm.sh/v135/@octokit/core@6.1.3/dist-types/types.d.ts?target=deno",
      "@octokit/oauth-app": "https://esm.sh/v135/@octokit/oauth-app@7.1.5?target=deno",
      "@octokit/plugin-paginate-graphql": "https://esm.sh/v135/@octokit/plugin-paginate-graphql@5.2.4?deps=@octokit/core@6.1.3",
      "@octokit/plugin-paginate-rest": "https://esm.sh/v135/@octokit/plugin-paginate-rest@11.4.0?target=deno",
      "@octokit/plugin-rest-endpoint-methods": "https://esm.sh/v135/@octokit/plugin-rest-endpoint-methods@13.3.0?target=deno",
      "@octokit/plugin-retry": "https://esm.sh/v135/@octokit/plugin-retry@7.1.3?target=deno",
      "@octokit/plugin-throttling": "https://esm.sh/v135/@octokit/plugin-throttling@9.4.0?target=deno",
      "@octokit/request-error": "https://esm.sh/v135/@octokit/request-error@6.1.6?target=deno",
      "@octokit/types": "https://esm.sh/v135/@octokit/types@13.7.0?target=deno",
      "@octokit/webhooks": "https://esm.sh/v135/@octokit/webhooks@13.4.2?target=deno"
    }
  }
}
```

I don't believe that this is an issue anymore
