### ISSUE TITLE
getContent tries to parse response as JSON even when request asks for raw data

### ISSUE THREAD

**Issue by a7medkamel** [octokit/octokit.js#210]
When we add the Accept header with 'application/vnd.github.v3.raw+json' we are expecting raw data back; but the response handler still tries to parse as JSON and when it fails and returns an error.

**Comment by pfister-vivintsolar** [comment]
This is happening to me also.

**Comment by mikedeboer** [comment]
This was fixed in a1115dc

**Comment by iwozzy** [comment]
@kaizensoze This is still happening when using `getBlob`, when the contents of the blob is a markdown file. I have the `Accept` header set to `application/vnd.github.v3.raw`

The result I get `Error: Unexpected token #`

The raw file is just:

`# Android-App`

**Comment by kaizensoze** [comment]
I've added a getRawBlob example [here](https://github.com/mikedeboer/node-github/blob/master/examples/getRawBlob.js). Let me know if it doesn't work for you.

**Comment by iwozzy** [comment]
Thank you. I tried that, and while I can get the `data` out of the response, the `err` object is as follows:

```
{ [Error: Unexpected token #]
  defaultMessage: 'Internal Server Error',
  message: 'Unexpected token #',
  code: '500',
  status: 'Internal Server Error',
  headers: undefined }
```

**Comment by kaizensoze** [comment]
Got it, I'll take a look.

**Comment by iwozzy** [comment]
Thank you. It just makes it harder to work with Promises (`bluebird.promisifyAll()`) in this case, since the `getBlobAsync()` function, with the `Accept` header set to `application/vnd.github.v3.raw` will reject.
