### ISSUE TITLE
Missing TypeScript Types in v14.0.0, v14.0.2

### ISSUE THREAD

**Issue by fbartho** [octokit/octokit.js#699]
I got excited to update to freshly released v14.0.0 to remove the rename-warning in our project, and went ahead and did the imports and ran the unit tests, and then realized there was a typescript compiler problem. Turns out the `index.d.ts` isn't being shipped with the new repo!

Context: https://github.com/danger/danger-js/issues/482

**Comment by gr2m** [comment]
oh my I’m so very sorry, I think I know exactly what the problem is! Let me fix it right away

Thanks for testing it out that quickly and for reporting the problem :)

**Comment by gr2m** [comment]
14.0.1 is on its way https://travis-ci.org/octokit/rest.js/builds/330145331

**Comment by fbartho** [comment]
@gr2m build failed because ~merge closed the PR branch~ XD

**Comment by gr2m** [comment]
oops wrong build sorry, this one: https://travis-ci.org/octokit/rest.js/builds/330145343

**Comment by gr2m** [comment]
okay now something is broken with the release, I’ll have to look into it later tonight, sorry to keep you waiting

**Comment by fbartho** [comment]
Woo!

**Comment by fbartho** [comment]
Haha no worries & no pressure, this is not a pressing issue for me @gr2m

**Comment by gr2m** [comment]
it should be fixed now :)

**Comment by fbartho** [comment]
Bad news @gr2m -- it's still broken with 14.0.2 :( 

```
node_modules/@octokit/rest/index.d.ts(26,5): error TS1110: Type expected.
26     ;
```

Because of:
```typescript
declare namespace Github {

  export interface AnyResponse {
// …snipped...
  }

  export type WellKnownHeader =
    ;

  export interface EmptyParams {
  }
```

**Comment by fbartho** [comment]
In commit: c6e5 index.js.flow.tpl had `#requestHeaders` deleted
https://github.com/octokit/rest.js/commit/c6e5#diff-6e934b6ee1e6925620b4e97cb684f4dfL3-L5

Looks like that needed to happen in the TypeScript [index.d.ts.tpl](https://github.com/octokit/rest.js/blob/25d0637e735cc317025c0d7a495cdb25267181ca/scripts/templates/index.d.ts.tpl#L26-L28) too! (Instead I think you get to delete the whole WellKnownHeaders type).

@gr2m -- please let me know if you'd like a new GitHub issue opened!

**Comment by gr2m** [comment]
I'm very sorry for the trouble 😞 

Could you maybe send a pull request to fix it? I’d very much appreciate it, I don’t use typescript myself. You should be able to git clone this repository, run `npm install ` and `npm run build:ts` in it. Then `cd` into your own project directory and run `npm link /path/to/rest.js` to install `@octokit/rest.js` from the local clone. Each time you change the typescript template file, make sure to run run `npm run build:ts` again.

**Comment by orta** [comment]
I'll get this

**Comment by fbartho** [comment]
Time zones can be good sometimes: I wake up, and there’s already a PR fixing things!
